services:

  portal:
    image: ferreiramabile/viaserra-portal:1.0-26175063
    ports:
      - "8063:80"
    restart: unless-stopped

  manutencao:
    build: ./manutencao
    ports:
      - "7063:80"
    restart: unless-stopped